%{
//THis is MY first LEX program
// Ashlesha Singh-24070521221
%}

%%

ZERO|Zero|zero {printf("0");}
ONE|One|one {printf("1");}
TWO|Two|two {printf("2");}
THREE|Three|three {printf("3");}
FOUR|Four|four {printf("4");}
FIVE|Five|five {printf("5");}
SIX|Six|six {printf("6");}
SEVEN|Seven|seven {printf("7");}
EIGHT|Eight|eight {printf("8");}
NINE|Nine|nine {printf("9");}
%%

int main(){
	yylex();
	return 0;
}
